export const UI_COPY = {
  english: {
    learningCompanion: "Learning companion",
    newDoubt: "New doubt",
    yourHistory: "Your history",
    open: "open",
    historyEmpty: "Your questions will appear here as you learn.",
    classroomMode: "Classroom mode",
    footer: "Made for curious minds, in every language.",
    answerLanguage: "Answer language",
    uiLanguage: "Interface language",
    autoDetect: "Auto-detect",
    askPlaceholder: "Ask anything...",
    addLater: "Add for Later",
    takePhoto: "Take photo",
    uploadImage: "Upload image",
    photoQuestion: "Photo question",
    answer: "Answer",
    pending: "Pending",
    answered: "Answered",
    solve: "Solve My",
    solving: "Solving",
    noHistory: "Your learning history will appear in the sidebar.",
    camera: "Camera",
    reviewPhoto: "Review your photo",
    cameraHint: "Position the question clearly inside the frame.",
    reviewHint: "Retake it or use this photo for your doubt.",
    close: "Close",
    back: "Back",
    cancel: "Cancel",
    capturePhoto: "Capture photo",
    retake: "Retake",
    usePhoto: "Use photo",
    processing: "Processing...",
    addingPhoto: "Adding photo...",
    earlierExplanation: "Earlier explanation",
    latestSimplified: "Latest simplified explanation",
    simplify: "Simplify Further",
    simplifying: "Simplifying...",
  },
  hindi: {
    learningCompanion: "पढ़ाई का साथी",
    newDoubt: "नई शंका",
    yourHistory: "आपका इतिहास",
    open: "बाकी",
    historyEmpty: "आपके सवाल यहां दिखाई देंगे।",
    classroomMode: "कक्षा मोड",
    footer: "हर भाषा में सीखने के लिए बनाया गया।",
    answerLanguage: "उत्तर की भाषा",
    uiLanguage: "ऐप की भाषा",
    autoDetect: "भाषा पहचानें",
    askPlaceholder: "कुछ भी पूछें...",
    addLater: "बाद के लिए जोड़ें",
    takePhoto: "फोटो लें",
    uploadImage: "फोटो अपलोड करें",
    photoQuestion: "फोटो वाला सवाल",
    answer: "उत्तर",
    pending: "बाकी सवाल",
    answered: "हल किए गए",
    solve: "हल करें",
    solving: "हल हो रहा है",
    noHistory: "आपका पढ़ाई का इतिहास यहां दिखाई देगा।",
    camera: "कैमरा",
    reviewPhoto: "अपनी फोटो देखें",
    cameraHint: "सवाल को फ्रेम के अंदर साफ रखें।",
    reviewHint: "फिर से फोटो लें या इस फोटो का इस्तेमाल करें।",
    close: "बंद करें",
    back: "वापस",
    cancel: "रद्द करें",
    capturePhoto: "फोटो खींचें",
    retake: "फिर से लें",
    usePhoto: "फोटो इस्तेमाल करें",
    processing: "तैयार हो रहा है...",
    addingPhoto: "फोटो जोड़ी जा रही है...",
    earlierExplanation: "पहला समझाया गया उत्तर",
    latestSimplified: "सबसे आसान नया उत्तर",
    simplify: "और आसान करें",
    simplifying: "आसान किया जा रहा है...",
  },
};

export function getUiCopy(language) {
  return UI_COPY[language] || UI_COPY.english;
}

export const INTERFACE_LANGUAGES = [
  ["english", "English"],
  ["hindi", "हिन्दी"],
  ["hinglish", "Hinglish"],
  ["bhojpuri", "भोजपुरी"],
  ["assamese", "অসমীয়া"],
  ["bengali", "বাংলা"],
  ["bodo", "बड़ो"],
  ["dogri", "डोगरी"],
  ["gujarati", "ગુજરાતી"],
  ["kannada", "ಕನ್ನಡ"],
  ["kashmiri", "कॉशुर / کٲشُر"],
  ["konkani", "कोंकणी"],
  ["maithili", "मैथिली"],
  ["malayalam", "മലയാളം"],
  ["manipuri", "মৈতৈলোন"],
  ["marathi", "मराठी"],
  ["nepali", "नेपाली"],
  ["odia", "ଓଡ଼ିଆ"],
  ["punjabi", "ਪੰਜਾਬੀ"],
  ["sanskrit", "संस्कृतम्"],
  ["santali", "ᱥᱟᱱᱛᱟᱲᱤ"],
  ["sindhi", "سنڌي"],
  ["tamil", "தமிழ்"],
  ["telugu", "తెలుగు"],
  ["urdu", "اُردُو"],
];
