export const UI_COPY = {
  english: {
    learningCompanion: "Learning companion",
    newDoubt: "New doubt",
    yourHistory: "Your history",
    open: "open",
    historyEmpty: "Your questions will appear here as you learn.",
    classroomMode: "Classroom mode",
    footer: "Made for curious minds, in every language.",
    answerLanguage: "Answer language",
    uiLanguage: "Interface language",
    autoDetect: "Auto-detect",
    askPlaceholder: "Ask anything...",
    addLater: "Add for Later",
    takePhoto: "Take photo",
    uploadImage: "Upload image",
    photoQuestion: "Photo question",
    answer: "Answer",
    pending: "Pending",
    answered: "Answered",
    solve: "Solve My",
    solving: "Solving",
    noHistory: "Your learning history will appear in the sidebar.",
    camera: "Camera",
    reviewPhoto: "Review your photo",
    cameraHint: "Position the question clearly inside the frame.",
    reviewHint: "Retake it or use this photo for your doubt.",
    close: "Close",
    back: "Back",
    cancel: "Cancel",
    capturePhoto: "Capture photo",
    retake: "Retake",
    usePhoto: "Use photo",
    processing: "Processing...",
    addingPhoto: "Adding photo...",
    earlierExplanation: "Earlier explanation",
    latestSimplified: "Latest simplified explanation",
    simplify: "Simplify Further",
    simplifying: "Simplifying...",
  },
  hindi: {
    learningCompanion: "पढ़ाई का साथी",
    newDoubt: "नई शंका",
    yourHistory: "आपका इतिहास",
    open: "बाकी",
    historyEmpty: "आपके सवाल यहां दिखाई देंगे।",
    classroomMode: "कक्षा मोड",
    footer: "हर भाषा में सीखने के लिए बनाया गया।",
    answerLanguage: "उत्तर की भाषा",
    uiLanguage: "ऐप की भाषा",
    autoDetect: "भाषा पहचानें",
    askPlaceholder: "कुछ भी पूछें...",
    addLater: "बाद के लिए जोड़ें",
    takePhoto: "फोटो लें",
    uploadImage: "फोटो अपलोड करें",
    photoQuestion: "फोटो वाला सवाल",
    answer: "उत्तर",
    pending: "बाकी सवाल",
    answered: "हल किए गए",
    solve: "हल करें",
    solving: "हल हो रहा है",
    noHistory: "आपका पढ़ाई का इतिहास यहां दिखाई देगा।",
    camera: "कैमरा",
    reviewPhoto: "अपनी फोटो देखें",
    cameraHint: "सवाल को फ्रेम के अंदर साफ रखें।",
    reviewHint: "फिर से फोटो लें या इस फोटो का इस्तेमाल करें।",
    close: "बंद करें",
    back: "वापस",
    cancel: "रद्द करें",
    capturePhoto: "फोटो खींचें",
    retake: "फिर से लें",
    usePhoto: "फोटो इस्तेमाल करें",
    processing: "तैयार हो रहा है...",
    addingPhoto: "फोटो जोड़ी जा रही है...",
    earlierExplanation: "पहला समझाया गया उत्तर",
    latestSimplified: "सबसे आसान नया उत्तर",
    simplify: "और आसान करें",
    simplifying: "आसान किया जा रहा है...",
  },
};

export function getUiCopy(language) {
  return { ...(UI_COPY[language] || UI_COPY.english), ...(WELCOME_COPY[language] || WELCOME_COPY.english) };
}

const WELCOME_COPY = {
  english: { welcomeTitle: "What are you curious about?", welcomeSubtitle: "Ask in the language and script you are most comfortable with. Add a photo of your notebook and we'll work through it together." },
  hindi: { welcomeTitle: "आप किस बारे में जानना चाहते हैं?", welcomeSubtitle: "अपनी पसंद की भाषा और लिपि में पूछें। अपनी नोटबुक की फोटो जोड़ें और हम इसे साथ में समझेंगे।" },
  hinglish: { welcomeTitle: "Aap kis baare mein curious hain?", welcomeSubtitle: "Apni pasand ki bhasha aur script mein poochhein. Notebook ki photo jodiye aur hum saath mein samjhenge." },
  bhojpuri: { welcomeTitle: "Rauwa ka jaanal chahat bani?", welcomeSubtitle: "Apne pasand ke bhasha aur lipi mein puchhin. Notebook ke photo jodi aur hum milke samjhi." },
  assamese: { welcomeTitle: "আপুনি কি জানিবলৈ উৎসুক?", welcomeSubtitle: "আপোনাৰ পছন্দৰ ভাষা আৰু লিপিত সোধক। নোটবুকৰ ফটো যোগ কৰক আৰু আমি একেলগে বুজিম।" },
  bengali: { welcomeTitle: "আপনি কী জানতে আগ্রহী?", welcomeSubtitle: "আপনার পছন্দের ভাষা ও লিপিতে প্রশ্ন করুন। খাতার ছবি যোগ করুন, আমরা একসঙ্গে বুঝব।" },
  bodo: { welcomeTitle: "नों मा बुङोबाव उत्सुक?", welcomeSubtitle: "नोंनि पसन्दनि राव आरो हांखोआव सों। नोंनि नोटबुकनि फोटो हो आरो जों लोगोसे बुङो।" },
  dogri: { welcomeTitle: "तुस केह् जानना चांह्दे ओ?", welcomeSubtitle: "अपनी पसंद दी भाशा ते लिपि च पुछो। नोटबुक दी फोटो जोड़ो ते अस इकठ्ठे समझांगे।" },
  gujarati: { welcomeTitle: "તમે શે વિશે જાણવા ઉત્સુક છો?", welcomeSubtitle: "તમારી પસંદની ભાષા અને લિપિમાં પૂછો. નોટબુકનો ફોટો ઉમેરો અને આપણે સાથે સમજીએ." },
  kannada: { welcomeTitle: "ನೀವು ಯಾವುದರ ಬಗ್ಗೆ ಕುತೂಹಲ ಹೊಂದಿದ್ದೀರಿ?", welcomeSubtitle: "ನಿಮಗೆ ಇಷ್ಟವಾದ ಭಾಷೆ ಮತ್ತು ಲಿಪಿಯಲ್ಲಿ ಕೇಳಿ. ನೋಟ್ಬುಕ್‌ನ ಫೋಟೋ ಸೇರಿಸಿ, ನಾವು ಒಟ್ಟಿಗೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳೋಣ." },
  kashmiri: { welcomeTitle: "تُہۍ کِیاہ سمجھنہٕ ہٕنٛد شوق چھُ؟", welcomeSubtitle: "پنٕنۍ پسند زبان تہٕ رسم الخطس منز پٕچھو۔ نوٹ بکُک فوٹو یِوو تہٕ أسۍ اکھ ساتھ سمجھن۔" },
  konkani: { welcomeTitle: "तुमका कितें जाणून घेवपाचें आसा?", welcomeSubtitle: "तुमच्या आवडत्या भाशेंत आनी लिपयेंत विचारात. नोटबुकाचो फोटो जोडात आनी आमी एकठांय समजून घेतले." },
  malayalam: { welcomeTitle: "നിങ്ങൾക്ക് എന്തിനെക്കുറിച്ചാണ് അറിയാൻ ആഗ്രഹം?", welcomeSubtitle: "നിങ്ങൾക്ക് സൗകര്യമുള്ള ഭാഷയിലും ലിപിയിലും ചോദിക്കൂ. നോട്ട്‌ബുക്കിന്റെ ഫോട്ടോ ചേർക്കൂ, നമുക്ക് ഒരുമിച്ച് മനസ്സിലാക്കാം." },
  manipuri: { welcomeTitle: "নহাক্না করিগুম্বা অমা খংনবা পাম্বিব্রা?", welcomeSubtitle: "নহাক্না পাম্বা লোন অমসুং ময়েক্তগী হংউ। নোটবুক্কী ফোটো হাপ্পু, অমসুং খংনবা তৌসি।" },
  marathi: { welcomeTitle: "तुम्हाला कशाबद्दल जाणून घ्यायचे आहे?", welcomeSubtitle: "तुमच्या आवडत्या भाषा आणि लिपीत विचारा. वहीचा फोटो जोडा आणि आपण एकत्र समजून घेऊ." },
  nepali: { welcomeTitle: "तपाईं के बारेमा जान्न उत्सुक हुनुहुन्छ?", welcomeSubtitle: "आफूलाई सहज लाग्ने भाषा र लिपिमा सोध्नुहोस्। कापीको फोटो थप्नुहोस् र हामी सँगै बुझ्नेछौं।" },
  odia: { welcomeTitle: "ଆପଣ କ’ଣ ଜାଣିବାକୁ ଆଗ୍ରହୀ?", welcomeSubtitle: "ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ଓ ଲିପିରେ ପଚାରନ୍ତୁ। ନୋଟବୁକ୍‌ର ଫଟୋ ଯୋଡନ୍ତୁ ଏବଂ ଆମେ ଏକାଠି ବୁଝିବା।" },
  punjabi: { welcomeTitle: "ਤੁਸੀਂ ਕਿਸ ਬਾਰੇ ਜਾਣਨ ਲਈ ਉਤਸੁਕ ਹੋ?", welcomeSubtitle: "ਆਪਣੀ ਪਸੰਦ ਦੀ ਭਾਸ਼ਾ ਅਤੇ ਲਿਪੀ ਵਿੱਚ ਪੁੱਛੋ। ਕਾਪੀ ਦੀ ਫੋਟੋ ਜੋੜੋ ਅਤੇ ਅਸੀਂ ਮਿਲ ਕੇ ਸਮਝਾਂਗੇ।" },
  sanskrit: { welcomeTitle: "भवान् किम् ज्ञातुम् इच्छति?", welcomeSubtitle: "भवतः रुचिकरभाषायां लिप्यां च पृच्छतु। पुस्तिकायाः चित्रं योजयतु, वयं सह अवगमिष्यावः।" },
  santali: { welcomeTitle: "ᱟᱢ ᱪᱮᱫ ᱵᱟᱝ ᱧᱮᱞ ᱮᱢ ᱥᱮᱫᱟᱭ?", welcomeSubtitle: "ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱪᱤᱠᱤ ᱨᱮ ᱯᱟᱹᱪᱩ। ᱱᱚᱴᱵᱩᱠ ᱯᱷᱚᱴᱚ ᱥᱮᱞᱮᱫ ᱢᱮ, ᱟᱵᱚ ᱢᱤᱫ ᱥᱟᱶ ᱵᱩᱡᱽᱦᱟᱣᱟ।" },
  sindhi: { welcomeTitle: "توهان ڇا ڄاڻڻ لاءِ شوقين آهيو؟", welcomeSubtitle: "پنهنجي پسند جي ٻولي ۽ رسم الخط ۾ پڇو. نوٽ بڪ جي تصوير شامل ڪريو ۽ اچو ته گڏجي سمجهون." },
  tamil: { welcomeTitle: "நீங்கள் எதைப் பற்றி அறிய ஆர்வமாக உள்ளீர்கள்?", welcomeSubtitle: "உங்களுக்கு வசதியான மொழி மற்றும் எழுத்தில் கேளுங்கள். நோட்டுப் புத்தகப் படத்தைச் சேர்த்து ஒன்றாகப் புரிந்துகொள்வோம்." },
  telugu: { welcomeTitle: "మీరు దేని గురించి తెలుసుకోవాలని ఆసక్తిగా ఉన్నారు?", welcomeSubtitle: "మీకు సౌకర్యమైన భాష మరియు లిపిలో అడగండి. నోట్బుక్ ఫోటోను జోడించండి, మనం కలిసి అర్థం చేసుకుందాం." },
  urdu: { welcomeTitle: "آپ کس بارے میں جاننے کے خواہش مند ہیں؟", welcomeSubtitle: "اپنی پسند کی زبان اور رسم الخط میں پوچھیں۔ اپنی نوٹ بک کی تصویر شامل کریں اور ہم مل کر سمجھیں گے۔" },
};

const EXTRA_UI_COPY = {
  assamese: { learningCompanion: "পঢ়াৰ সংগী", newDoubt: "নতুন প্ৰশ্ন", yourHistory: "আপোনাৰ ইতিহাস", historyEmpty: "আপোনাৰ প্ৰশ্ন ইয়াত দেখা যাব।", classroomMode: "শ্ৰেণীকোঠা মোড", answerLanguage: "উত্তৰৰ ভাষা", uiLanguage: "এপৰ ভাষা", askPlaceholder: "যিকোনো কথা সোধক...", addLater: "পিছত যোগ কৰক", takePhoto: "ফটো লওক", uploadImage: "ফটো আপলোড কৰক", answer: "উত্তৰ", pending: "বাকী", answered: "উত্তৰ দিয়া হৈছে", solve: "সমাধান কৰক", solving: "সমাধান হৈ আছে", camera: "কেমেৰা", close: "বন্ধ কৰক", back: "উভতি যাওক", cancel: "বাতিল", capturePhoto: "ফটো লওক", retake: "পুনৰ লওক", usePhoto: "ফটো ব্যৱহাৰ কৰক", simplify: "আৰু সহজ কৰক", simplifying: "সহজ কৰা হৈ আছে..." },
  bodo: { learningCompanion: "फरायसाफोरनि साजाय", newDoubt: "गोदान संदेह", yourHistory: "नोंनि इतिहास", historyEmpty: "नोंनि संदेहफोर बेयाव दिन्थिगोन।", classroomMode: "क्लासरुम मोड", answerLanguage: "फरायसाफोरनि राव", uiLanguage: "एपनि राव", askPlaceholder: "जेबो सोध...", addLater: "उनाव हो", takePhoto: "फोटो ल", uploadImage: "फोटो अपलोड खालाम", answer: "फिननाय", pending: "बां", answered: "फिननाय होदों", solve: "सोलुसन खालाम", solving: "सोलुसन जादों", camera: "केमेरा", close: "बन्द खालाम", back: "उनाव", cancel: "बातिल", capturePhoto: "फोटो ल", retake: "दाब्लाय ल", usePhoto: "फोटो बाहाय", simplify: "गोबां सोखां खालाम", simplifying: "सोखां जादों" },
  dogri: { learningCompanion: "पढ़ाई दा साथी", newDoubt: "नमां सवाल", yourHistory: "तुंदा इतिहास", historyEmpty: "तुंदे सवाल इत्थे दिक्खन गे।", classroomMode: "क्लासरूम मोड", answerLanguage: "जवाब दी भाशा", uiLanguage: "ऐप दी भाशा", askPlaceholder: "कुछ बी पुछो...", addLater: "बाद च जोड़ो", takePhoto: "फोटो खिचो", uploadImage: "फोटो अपलोड करो", answer: "जवाब", pending: "बाकी", answered: "जवाब दित्ता", solve: "हल करो", solving: "हल होआ करदा", camera: "कैमरा", close: "बंद करो", back: "पिच्छे", cancel: "रद्द", capturePhoto: "फोटो खिचो", retake: "फेर खिचो", usePhoto: "फोटो बरतो", simplify: "होर सौखा करो", simplifying: "सौखा होआ करदा" },
  kashmiri: { learningCompanion: "پڑھائی ہٕند ساتھی", newDoubt: "نَو سوال", yourHistory: "تُہٕند تاریخ", historyEmpty: "تُہٕند سوال یتھ دِکھن۔", classroomMode: "کلاس روم موڈ", answerLanguage: "جوابُک زبان", uiLanguage: "ایپُک زبان", askPlaceholder: "کُنہِ تہٕ پٕچھو...", addLater: "پتہٕ جمع کٔر", takePhoto: "فوٹو کٔر", uploadImage: "فوٹو اپلوڈ کٔر", answer: "جواب", pending: "باقی", answered: "جواب دِت", solve: "حل کٔر", solving: "حل گژھان", camera: "کیمرا", close: "بند کٔر", back: "پتہٕ", cancel: "منسوخ", capturePhoto: "فوٹو کٔر", retake: "دوبارہ کٔر", usePhoto: "فوٹو استعمال کٔر", simplify: "مزید آسان کٔر", simplifying: "آسان گژھان" },
  konkani: { learningCompanion: "शिकपाचो साथी", newDoubt: "नवी शंका", yourHistory: "तुमचो इतिहास", historyEmpty: "तुमचे प्रस्न हांगा दिसतले.", classroomMode: "वर्ग मोड", answerLanguage: "जापाची भास", uiLanguage: "ऍपाची भास", askPlaceholder: "कितेंय विचारात...", addLater: "मागीर जोडात", takePhoto: "फोटो काडात", uploadImage: "फोटो अपलोड करात", answer: "जाप", pending: "उरिल्ले", answered: "जाप मेळ्ळो", solve: "सोडोवात", solving: "सोडयतात", camera: "कॅमेरा", close: "बंद करात", back: "फाटीं", cancel: "रद्द", capturePhoto: "फोटो काडात", retake: "परत काडात", usePhoto: "फोटो वापरात", simplify: "आनी सोपें करात", simplifying: "सोपें जाता" },
  manipuri: { learningCompanion: "পাঠক্কী শরুক", newDoubt: "অনৌবা ৱাহং", yourHistory: "নহাক্কী ইতিহাস", historyEmpty: "নহাক্কী ৱাহংসিং মফম অসিদা উতলগনি।", classroomMode: "ক্লাসরুম মোড", answerLanguage: "ৱাফমগী লোন", uiLanguage: "এপগী লোন", askPlaceholder: "করিগুম্বা অমা হংউ...", addLater: "মতুংদা হাপ্পু", takePhoto: "ফোটো লৌ", uploadImage: "ফোটো অপলোড তৌ", answer: "খুৎলাই", pending: "থোকপা", answered: "খুৎলাই পীরবনি", solve: "শেমদোকউ", solving: "শেমদোক্লি", camera: "কেমেরা", close: "লৌথোকউ", back: "মতুংদা", cancel: "ক্যান্সেল", capturePhoto: "ফোটো লৌ", retake: "অমুক লৌ", usePhoto: "ফোটো শিজিন্নৌ", simplify: "হেন্না ইজি তৌ", simplifying: "ইজি তৌরি" },
  sanskrit: { learningCompanion: "अध्ययनसहचरः", newDoubt: "नवः प्रश्नः", yourHistory: "भवतः इतिहासः", historyEmpty: "भवतः प्रश्नाः अत्र दृश्यन्ते।", classroomMode: "कक्षामोडः", answerLanguage: "उत्तरभाषा", uiLanguage: "अनुप्रयोगभाषा", askPlaceholder: "किमपि पृच्छतु...", addLater: "पश्चात् योजयतु", takePhoto: "चित्रं गृह्णातु", uploadImage: "चित्रम् उपलोड् करोतु", answer: "उत्तरम्", pending: "अवशिष्टम्", answered: "उत्तरितम्", solve: "समाधत्ताम्", solving: "समाधीयते", camera: "चित्रग्राहकम्", close: "पिधत्तु", back: "पश्चात्", cancel: "निरस्यतु", capturePhoto: "चित्रं गृह्णातु", retake: "पुनः गृह्णातु", usePhoto: "चित्रम् उपयुङ्क्ताम्", simplify: "अधिकं सरलं करोतु", simplifying: "सरलीक्रियते" },
  santali: { learningCompanion: "ᱥᱮᱫᱟᱭ ᱥᱟᱹᱜᱟᱹᱭ", newDoubt: "ᱱᱟᱣᱟ ᱥᱟᱹᱢᱟᱹᱭ", yourHistory: "ᱟᱢᱟᱜ ᱦᱤᱥᱴᱚᱨᱤ", historyEmpty: "ᱟᱢᱟᱜ ᱥᱟᱹᱢᱟᱹᱭ ᱱᱚᱣᱟ ᱨᱮ ᱧᱮᱞᱚᱜᱼᱟ।", classroomMode: "ᱠᱞᱟᱥᱨᱩᱢ ᱢᱳᱰ", answerLanguage: "ᱡᱚᱵᱟᱵ ᱨᱮᱭᱟᱜ ᱯᱟᱹᱨᱥᱤ", uiLanguage: "ᱮᱯ ᱯᱟᱹᱨᱥᱤ", askPlaceholder: "ᱡᱟᱦᱟᱱ ᱵᱟᱝ ᱯᱟᱹᱸᱪᱩ...", addLater: "ᱛᱟᱭᱚᱢ ᱥᱮᱞᱮᱫ", takePhoto: "ᱯᱷᱚᱴᱚ ᱞᱟᱹᱭ", uploadImage: "ᱯᱷᱚᱴᱚ ᱟᱯᱞᱳᱰ", answer: "ᱡᱚᱵᱟᱵ", pending: "ᱵᱟᱹᱠᱤ", answered: "ᱡᱚᱵᱟᱵ ᱮᱢ", solve: "ᱥᱚᱞᱵ", solving: "ᱥᱚᱞᱵ ᱦᱚᱪᱚᱜᱼᱟ", camera: "ᱠᱮᱢᱮᱨᱟ", close: "ᱵᱚᱸᱫ", back: "ᱛᱟᱭᱚᱢ", cancel: "ᱵᱟᱹᱛᱤᱞ", capturePhoto: "ᱯᱷᱚᱴᱚ ᱞᱟᱹᱭ", retake: "ᱫᱚᱵᱟᱨᱟ ᱞᱟᱹᱭ", usePhoto: "ᱯᱷᱚᱴᱚ ᱵᱟᱹᱭᱦᱟᱹᱨ", simplify: "ᱟᱹᱨᱚ ᱥᱚᱨᱞ", simplifying: "ᱥᱚᱨᱞ ᱦᱚᱪᱚᱜᱼᱟ" },
  sindhi: { learningCompanion: "پڙهائي جو ساٿي", newDoubt: "نئون سوال", yourHistory: "توهان جي تاريخ", historyEmpty: "توهان جا سوال هتي نظر ايندا.", classroomMode: "ڪلاس روم موڊ", answerLanguage: "جواب جي ٻولي", uiLanguage: "ايپ جي ٻولي", askPlaceholder: "ڪجهه به پڇو...", addLater: "پوءِ شامل ڪريو", takePhoto: "فوٽو وٺو", uploadImage: "فوٽو اپلوڊ ڪريو", answer: "جواب", pending: "باقي", answered: "جواب ڏنو ويو", solve: "حل ڪريو", solving: "حل ٿي رهيو آهي", camera: "ڪئميرا", close: "بند ڪريو", back: "واپس", cancel: "رد", capturePhoto: "فوٽو وٺو", retake: "ٻيهر وٺو", usePhoto: "فوٽو استعمال ڪريو", simplify: "وڌيڪ آسان ڪريو", simplifying: "آسان ٿي رهيو آهي" },
  hinglish: { learningCompanion: "Padhai ka saathi", newDoubt: "Naya sawaal", yourHistory: "Aapka history", historyEmpty: "Aapke sawaal yahan dikhenge.", classroomMode: "Classroom mode", footer: "Har bhasha mein seekhne ke liye bana.", answerLanguage: "Answer ki bhasha", uiLanguage: "App ki bhasha", autoDetect: "Bhasha pehchanein", askPlaceholder: "Kuch bhi poochhein...", addLater: "Baad ke liye joden", takePhoto: "Photo lein", uploadImage: "Photo upload karein", photoQuestion: "Photo sawaal", answer: "Jawaab", pending: "Baaki", answered: "Hal ho gaya", solve: "Hal karein", solving: "Hal ho raha hai", noHistory: "Aapki learning history yahan dikhegi.", camera: "Camera", close: "Band karein", back: "Wapas", cancel: "Cancel", capturePhoto: "Photo kheecho", retake: "Phir se lein", usePhoto: "Photo use karein", processing: "Taiyaar ho raha hai...", addingPhoto: "Photo add ho raha hai...", simplify: "Aur aasaan karein", simplifying: "Aasaan ho raha hai..." },
  bhojpuri: { learningCompanion: "Padhai ke saathi", newDoubt: "Naya sawaal", yourHistory: "Tohar history", historyEmpty: "Tohar sawaal ihe dekhaai.", classroomMode: "Classroom mode", footer: "Har bhasha mein sikhe khatir banal.", answerLanguage: "Jawaab ke bhasha", uiLanguage: "App ke bhasha", autoDetect: "Bhasha pahichani", askPlaceholder: "Kuchhu puchhin...", addLater: "Baad mein jodi", takePhoto: "Photo lihi", uploadImage: "Photo upload kari", photoQuestion: "Photo wala sawaal", answer: "Jawaab", pending: "Baaki", answered: "Jawaab milal", solve: "Hal kari", solving: "Hal ho rahal ba", noHistory: "Tohar padhai ke history ihe dekhaai.", camera: "Camera", close: "Band kari", back: "Pichhe", cancel: "Radd kari", capturePhoto: "Photo khinchi", retake: "Dobaara lihi", usePhoto: "Photo lagai", processing: "Taiyaar ho rahal ba...", addingPhoto: "Photo jod rahal ba...", simplify: "Aur aasaan kari", simplifying: "Aasaan ho rahal ba..." },
  bengali: { learningCompanion: "পড়াশোনার সঙ্গী", newDoubt: "নতুন প্রশ্ন", yourHistory: "আপনার ইতিহাস", historyEmpty: "আপনার প্রশ্নগুলি এখানে দেখা যাবে।", classroomMode: "ক্লাসরুম মোড", footer: "প্রতিটি ভাষায় শেখার জন্য তৈরি।", answerLanguage: "উত্তরের ভাষা", uiLanguage: "অ্যাপের ভাষা", autoDetect: "ভাষা শনাক্ত করুন", askPlaceholder: "যেকোনো প্রশ্ন করুন...", addLater: "পরে যোগ করুন", takePhoto: "ছবি তুলুন", uploadImage: "ছবি আপলোড করুন", photoQuestion: "ছবির প্রশ্ন", answer: "উত্তর", pending: "বাকি", answered: "উত্তর দেওয়া হয়েছে", solve: "সমাধান করুন", solving: "সমাধান হচ্ছে", noHistory: "আপনার পড়াশোনার ইতিহাস এখানে দেখা যাবে।", camera: "ক্যামেরা", close: "বন্ধ করুন", back: "পিছনে", cancel: "বাতিল", capturePhoto: "ছবি তুলুন", retake: "আবার তুলুন", usePhoto: "ছবি ব্যবহার করুন", processing: "প্রস্তুত হচ্ছে...", addingPhoto: "ছবি যোগ হচ্ছে...", simplify: "আরও সহজ করুন", simplifying: "সহজ করা হচ্ছে..." },
  gujarati: { learningCompanion: "અભ્યાસનો સાથી", newDoubt: "નવી શંકા", yourHistory: "તમારો ઇતિહાસ", historyEmpty: "તમારા પ્રશ્નો અહીં દેખાશે.", classroomMode: "વર્ગખંડ મોડ", footer: "દરેક ભાષામાં શીખવા માટે બનાવ્યું.", answerLanguage: "જવાબની ભાષા", uiLanguage: "એપની ભાષા", autoDetect: "ભાષા ઓળખો", askPlaceholder: "કંઈ પણ પૂછો...", addLater: "પછી ઉમેરો", takePhoto: "ફોટો લો", uploadImage: "ફોટો અપલોડ કરો", photoQuestion: "ફોટાનો પ્રશ્ન", answer: "જવાબ", pending: "બાકી", answered: "જવાબ આપ્યો", solve: "ઉકેલો", solving: "ઉકેલાઈ રહ્યું છે", noHistory: "તમારો અભ્યાસ ઇતિહાસ અહીં દેખાશે.", camera: "કેમેરા", close: "બંધ કરો", back: "પાછા", cancel: "રદ કરો", capturePhoto: "ફોટો લો", retake: "ફરી લો", usePhoto: "ફોટો વાપરો", processing: "તૈયાર થઈ રહ્યું છે...", addingPhoto: "ફોટો ઉમેરાઈ રહ્યો છે...", simplify: "વધુ સરળ કરો", simplifying: "સરળ થઈ રહ્યું છે..." },
  marathi: { learningCompanion: "अभ्यासाचा साथी", newDoubt: "नवीन शंका", yourHistory: "तुमचा इतिहास", historyEmpty: "तुमचे प्रश्न येथे दिसतील.", classroomMode: "वर्गखोली मोड", footer: "प्रत्येक भाषेत शिकण्यासाठी बनवलेले.", answerLanguage: "उत्तराची भाषा", uiLanguage: "अॅपची भाषा", autoDetect: "भाषा ओळखा", askPlaceholder: "काहीही विचारा...", addLater: "नंतर जोडा", takePhoto: "फोटो काढा", uploadImage: "फोटो अपलोड करा", photoQuestion: "फोटोमधील प्रश्न", answer: "उत्तर", pending: "प्रलंबित", answered: "उत्तर दिले", solve: "सोडवा", solving: "सोडवत आहे", noHistory: "तुमचा अभ्यास इतिहास येथे दिसेल.", camera: "कॅमेरा", close: "बंद करा", back: "मागे", cancel: "रद्द करा", capturePhoto: "फोटो काढा", retake: "पुन्हा काढा", usePhoto: "फोटो वापरा", processing: "तयार होत आहे...", addingPhoto: "फोटो जोडत आहे...", simplify: "अधिक सोपे करा", simplifying: "सोपे करत आहे..." },
  punjabi: { learningCompanion: "ਪੜ੍ਹਾਈ ਦਾ ਸਾਥੀ", newDoubt: "ਨਵਾਂ ਸਵਾਲ", yourHistory: "ਤੁਹਾਡਾ ਇਤਿਹਾਸ", historyEmpty: "ਤੁਹਾਡੇ ਸਵਾਲ ਇੱਥੇ ਦਿਖਣਗੇ।", classroomMode: "ਕਲਾਸਰੂਮ ਮੋਡ", footer: "ਹਰ ਭਾਸ਼ਾ ਵਿੱਚ ਸਿੱਖਣ ਲਈ ਬਣਾਇਆ।", answerLanguage: "ਜਵਾਬ ਦੀ ਭਾਸ਼ਾ", uiLanguage: "ਐਪ ਦੀ ਭਾਸ਼ਾ", autoDetect: "ਭਾਸ਼ਾ ਪਛਾਣੋ", askPlaceholder: "ਕੁਝ ਵੀ ਪੁੱਛੋ...", addLater: "ਬਾਅਦ ਵਿੱਚ ਜੋੜੋ", takePhoto: "ਫੋਟੋ ਖਿੱਚੋ", uploadImage: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ", photoQuestion: "ਫੋਟੋ ਵਾਲਾ ਸਵਾਲ", answer: "ਜਵਾਬ", pending: "ਬਾਕੀ", answered: "ਹੱਲ ਹੋ ਗਿਆ", solve: "ਹੱਲ ਕਰੋ", solving: "ਹੱਲ ਹੋ ਰਿਹਾ ਹੈ", noHistory: "ਤੁਹਾਡੀ ਪੜ੍ਹਾਈ ਦੀ ਹਿਸਟਰੀ ਇੱਥੇ ਦਿਖੇਗੀ।", camera: "ਕੈਮਰਾ", close: "ਬੰਦ ਕਰੋ", back: "ਵਾਪਸ", cancel: "ਰੱਦ ਕਰੋ", capturePhoto: "ਫੋਟੋ ਖਿੱਚੋ", retake: "ਦੁਬਾਰਾ ਖਿੱਚੋ", usePhoto: "ਫੋਟੋ ਵਰਤੋ", processing: "ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ...", addingPhoto: "ਫੋਟੋ ਜੋੜੀ ਜਾ ਰਹੀ ਹੈ...", simplify: "ਹੋਰ ਸੌਖਾ ਕਰੋ", simplifying: "ਸੌਖਾ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ..." },
  tamil: { learningCompanion: "கற்றல் துணை", newDoubt: "புதிய கேள்வி", yourHistory: "உங்கள் வரலாறு", historyEmpty: "உங்கள் கேள்விகள் இங்கே தோன்றும்.", classroomMode: "வகுப்பு முறை", footer: "ஒவ்வொரு மொழியிலும் கற்க உருவாக்கப்பட்டது.", answerLanguage: "பதிலின் மொழி", uiLanguage: "செயலி மொழி", autoDetect: "மொழியை கண்டறி", askPlaceholder: "எதையும் கேளுங்கள்...", addLater: "பின்னர் சேர்க்கவும்", takePhoto: "புகைப்படம் எடுக்கவும்", uploadImage: "படத்தை பதிவேற்றவும்", photoQuestion: "படக் கேள்வி", answer: "பதில்", pending: "நிலுவையில்", answered: "பதிலளிக்கப்பட்டது", solve: "தீர்க்கவும்", solving: "தீர்க்கப்படுகிறது", noHistory: "உங்கள் கற்றல் வரலாறு இங்கே தோன்றும்.", camera: "கேமரா", close: "மூடு", back: "பின்செல்", cancel: "ரத்து", capturePhoto: "புகைப்படம் எடுக்கவும்", retake: "மீண்டும் எடுக்கவும்", usePhoto: "படத்தைப் பயன்படுத்தவும்", processing: "தயாராகிறது...", addingPhoto: "படம் சேர்க்கப்படுகிறது...", simplify: "மேலும் எளிமையாக்கவும்", simplifying: "எளிமையாக்கப்படுகிறது..." },
  telugu: { learningCompanion: "చదువు సహచరుడు", newDoubt: "కొత్త సందేహం", yourHistory: "మీ చరిత్ర", historyEmpty: "మీ ప్రశ్నలు ఇక్కడ కనిపిస్తాయి.", classroomMode: "తరగతి మోడ్", footer: "ప్రతి భాషలో నేర్చుకోవడానికి రూపొందించబడింది.", answerLanguage: "జవాబు భాష", uiLanguage: "యాప్ భాష", autoDetect: "భాషను గుర్తించండి", askPlaceholder: "ఏదైనా అడగండి...", addLater: "తర్వాత జోడించండి", takePhoto: "ఫోటో తీయండి", uploadImage: "ఫోటో అప్లోడ్ చేయండి", photoQuestion: "ఫోటో ప్రశ్న", answer: "జవాబు", pending: "పెండింగ్", answered: "సమాధానం ఇచ్చారు", solve: "పరిష్కరించండి", solving: "పరిష్కరిస్తోంది", noHistory: "మీ చదువు చరిత్ర ఇక్కడ కనిపిస్తుంది.", camera: "కెమెరా", close: "మూసివేయి", back: "వెనక్కి", cancel: "రద్దు", capturePhoto: "ఫోటో తీయండి", retake: "మళ్లీ తీయండి", usePhoto: "ఫోటో వాడండి", processing: "సిద్ధమవుతోంది...", addingPhoto: "ఫోటో జోడిస్తోంది...", simplify: "మరింత సులభం చేయండి", simplifying: "సులభం చేస్తోంది..." },
  malayalam: { learningCompanion: "പഠന സഹായി", newDoubt: "പുതിയ സംശയം", yourHistory: "നിങ്ങളുടെ ചരിത്രം", historyEmpty: "നിങ്ങളുടെ ചോദ്യങ്ങൾ ഇവിടെ കാണാം.", classroomMode: "ക്ലാസ് മുറി മോഡ്", footer: "എല്ലാ ഭാഷകളിലും പഠിക്കാൻ നിർമ്മിച്ചത്.", answerLanguage: "ഉത്തരത്തിന്റെ ഭാഷ", uiLanguage: "ആപ്പിന്റെ ഭാഷ", autoDetect: "ഭാഷ കണ്ടെത്തുക", askPlaceholder: "എന്തും ചോദിക്കൂ...", addLater: "പിന്നീട് ചേർക്കുക", takePhoto: "ഫോട്ടോ എടുക്കുക", uploadImage: "ഫോട്ടോ അപ്ലോഡ് ചെയ്യുക", photoQuestion: "ഫോട്ടോ ചോദ്യം", answer: "ഉത്തരം", pending: "തീർപ്പാക്കാത്തത്", answered: "ഉത്തരം നൽകി", solve: "പരിഹരിക്കുക", solving: "പരിഹരിക്കുന്നു", noHistory: "നിങ്ങളുടെ പഠന ചരിത്രം ഇവിടെ കാണാം.", camera: "ക്യാമറ", close: "അടയ്ക്കുക", back: "തിരികെ", cancel: "റദ്ദാക്കുക", capturePhoto: "ഫോട്ടോ എടുക്കുക", retake: "വീണ്ടും എടുക്കുക", usePhoto: "ഫോട്ടോ ഉപയോഗിക്കുക", processing: "തയ്യാറാകുന്നു...", addingPhoto: "ഫോട്ടോ ചേർക്കുന്നു...", simplify: "കൂടുതൽ ലളിതമാക്കുക", simplifying: "ലളിതമാക്കുന്നു..." },
  nepali: { learningCompanion: "सिकाइ साथी", newDoubt: "नयाँ प्रश्न", yourHistory: "तपाईंको इतिहास", historyEmpty: "तपाईंका प्रश्नहरू यहाँ देखिनेछन्।", classroomMode: "कक्षा मोड", footer: "हरेक भाषामा सिक्नका लागि बनाइएको।", answerLanguage: "उत्तरको भाषा", uiLanguage: "एपको भाषा", autoDetect: "भाषा पहिचान गर्नुहोस्", askPlaceholder: "जे पनि सोध्नुहोस्...", addLater: "पछि थप्नुहोस्", takePhoto: "फोटो खिच्नुहोस्", uploadImage: "फोटो अपलोड गर्नुहोस्", photoQuestion: "फोटो प्रश्न", answer: "उत्तर", pending: "बाँकी", answered: "उत्तर दिइयो", solve: "समाधान गर्नुहोस्", solving: "समाधान हुँदैछ", noHistory: "तपाईंको पढाइको इतिहास यहाँ देखिनेछ।", camera: "क्यामेरा", close: "बन्द गर्नुहोस्", back: "पछाडि", cancel: "रद्द", capturePhoto: "फोटो खिच्नुहोस्", retake: "फेरि खिच्नुहोस्", usePhoto: "फोटो प्रयोग गर्नुहोस्", processing: "तयार हुँदैछ...", addingPhoto: "फोटो थपिँदैछ...", simplify: "अझ सरल बनाउनुहोस्", simplifying: "सरल बनाउँदैछ..." },
  odia: { learningCompanion: "ପଢ଼ା ସାଥୀ", newDoubt: "ନୂଆ ପ୍ରଶ୍ନ", yourHistory: "ଆପଣଙ୍କ ଇତିହାସ", historyEmpty: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ଏଠାରେ ଦେଖାଯିବ।", classroomMode: "ଶ୍ରେଣୀ ମୋଡ୍", footer: "ପ୍ରତ୍ୟେକ ଭାଷାରେ ଶିଖିବା ପାଇଁ ତିଆରି।", answerLanguage: "ଉତ୍ତରର ଭାଷା", uiLanguage: "ଆପ୍ ଭାଷା", autoDetect: "ଭାଷା ଚିହ୍ନନ୍ତୁ", askPlaceholder: "ଯାହା ଇଚ୍ଛା ପଚାରନ୍ତୁ...", addLater: "ପରେ ଯୋଡନ୍ତୁ", takePhoto: "ଫଟୋ ନିଅନ୍ତୁ", uploadImage: "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ", photoQuestion: "ଫଟୋ ପ୍ରଶ୍ନ", answer: "ଉତ୍ତର", pending: "ବାକି", answered: "ଉତ୍ତର ଦିଆଗଲା", solve: "ସମାଧାନ କରନ୍ତୁ", solving: "ସମାଧାନ ହେଉଛି", noHistory: "ଆପଣଙ୍କ ପଢ଼ା ଇତିହାସ ଏଠାରେ ଦେଖାଯିବ।", camera: "କ୍ୟାମେରା", close: "ବନ୍ଦ କରନ୍ତୁ", back: "ପଛକୁ", cancel: "ବାତିଲ", capturePhoto: "ଫଟୋ ନିଅନ୍ତୁ", retake: "ପୁଣି ନିଅନ୍ତୁ", usePhoto: "ଫଟୋ ବ୍ୟବହାର କରନ୍ତୁ", processing: "ପ୍ରସ୍ତୁତ ହେଉଛି...", addingPhoto: "ଫଟୋ ଯୋଡାଯାଉଛି...", simplify: "ଆହୁରି ସରଳ କରନ୍ତୁ", simplifying: "ସରଳ କରାଯାଉଛି..." },
  kannada: { learningCompanion: "ಕಲಿಕೆಯ ಸಂಗಾತಿ", newDoubt: "ಹೊಸ ಪ್ರಶ್ನೆ", yourHistory: "ನಿಮ್ಮ ಇತಿಹಾಸ", historyEmpty: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.", classroomMode: "ತರಗತಿ ಮೋಡ್", footer: "ಪ್ರತಿ ಭಾಷೆಯಲ್ಲಿ ಕಲಿಯಲು ನಿರ್ಮಿಸಲಾಗಿದೆ.", answerLanguage: "ಉತ್ತರದ ಭಾಷೆ", uiLanguage: "ಆ್ಯಪ್ ಭಾಷೆ", autoDetect: "ಭಾಷೆ ಗುರುತಿಸಿ", askPlaceholder: "ಏನಾದರೂ ಕೇಳಿ...", addLater: "ನಂತರ ಸೇರಿಸಿ", takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ", uploadImage: "ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ", photoQuestion: "ಫೋಟೋ ಪ್ರಶ್ನೆ", answer: "ಉತ್ತರ", pending: "ಬಾಕಿ", answered: "ಉತ್ತರಿಸಲಾಗಿದೆ", solve: "ಪರಿಹರಿಸಿ", solving: "ಪರಿಹರಿಸಲಾಗುತ್ತಿದೆ", noHistory: "ನಿಮ್ಮ ಕಲಿಕೆಯ ಇತಿಹಾಸ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.", camera: "ಕ್ಯಾಮೆರಾ", close: "ಮುಚ್ಚಿ", back: "ಹಿಂದಕ್ಕೆ", cancel: "ರದ್ದು", capturePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ", retake: "ಮತ್ತೆ ತೆಗೆಯಿರಿ", usePhoto: "ಫೋಟೋ ಬಳಸಿ", processing: "ಸಿದ್ಧವಾಗುತ್ತಿದೆ...", addingPhoto: "ಫೋಟೋ ಸೇರಿಸಲಾಗುತ್ತಿದೆ...", simplify: "ಇನ್ನಷ್ಟು ಸರಳಗೊಳಿಸಿ", simplifying: "ಸರಳಗೊಳಿಸಲಾಗುತ್ತಿದೆ..." },
  urdu: { learningCompanion: "تعلیم کا ساتھی", newDoubt: "نیا سوال", yourHistory: "آپ کی تاریخ", historyEmpty: "آپ کے سوالات یہاں دکھائی دیں گے۔", classroomMode: "کلاس روم موڈ", footer: "ہر زبان میں سیکھنے کے لیے بنایا گیا۔", answerLanguage: "جواب کی زبان", uiLanguage: "ایپ کی زبان", autoDetect: "زبان پہچانیں", askPlaceholder: "کچھ بھی پوچھیں...", addLater: "بعد کے لیے شامل کریں", takePhoto: "تصویر لیں", uploadImage: "تصویر اپ لوڈ کریں", photoQuestion: "تصویر کا سوال", answer: "جواب", pending: "زیر التوا", answered: "جواب دیا گیا", solve: "حل کریں", solving: "حل ہو رہا ہے", noHistory: "آپ کی پڑھائی کی تاریخ یہاں دکھائی دے گی۔", camera: "کیمرہ", close: "بند کریں", back: "واپس", cancel: "منسوخ", capturePhoto: "تصویر لیں", retake: "دوبارہ لیں", usePhoto: "تصویر استعمال کریں", processing: "تیار ہو رہا ہے...", addingPhoto: "تصویر شامل ہو رہی ہے...", simplify: "مزید آسان کریں", simplifying: "آسان کیا جا رہا ہے..." },
};

Object.entries(EXTRA_UI_COPY).forEach(([language, overrides]) => {
  UI_COPY[language] = { ...UI_COPY.english, ...overrides };
});

export const INTERFACE_LANGUAGES = [
  ["english", "English"], ["hindi", "हिन्दी"], ["hinglish", "Hinglish"], ["bhojpuri", "भोजपुरी"],
  ["assamese", "অসমীয়া"], ["bengali", "বাংলা"], ["bodo", "बड़ो"], ["dogri", "डोगरी"], ["gujarati", "ગુજરાતી"],
  ["kannada", "ಕನ್ನಡ"], ["kashmiri", "کٲشُر"], ["konkani", "कोंकणी"], ["malayalam", "മലയാളം"], ["manipuri", "মৈতৈলোন"],
  ["marathi", "मराठी"], ["nepali", "नेपाली"], ["odia", "ଓଡ଼ିଆ"], ["punjabi", "ਪੰਜਾਬੀ"], ["sanskrit", "संस्कृतम्"],
  ["santali", "ᱥᱟᱱᱛᱟᱲᱤ"], ["sindhi", "سنڌي"], ["tamil", "தமிழ்"], ["telugu", "తెలుగు"], ["urdu", "اُردُو"],
];
